joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

ur5e_shoulder_pan_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

ur5e_shoulder_lift_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_shoulder_lift_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

ur5e_elbow_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_elbow_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

ur5e_wrist_1_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_wrist_1_joint
  pid: {p: 50.0, i: 0.01, d: 5.0}

ur5e_wrist_2_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_wrist_2_joint
  pid: {p: 50.0, i: 0.01, d: 5.0}

ur5e_wrist_3_position_controller:
  type: position_controllers/JointPositionController
  joint: ur5e_wrist_3_joint
  pid: {p: 30.0, i: 0.01, d: 2.0}

gripper_finger1_controller:
  type: position_controllers/JointPositionController
  joint: gripper_finger1_joint
  pid: {p: 50.0, i: 0.01, d: 5.0}


# summit_velocity_controller:
#   type: velocity_controllers/JointGroupVelocityController
#   joints:
#     - summit_xl_front_left_wheel_joint
#     - summit_xl_front_right_wheel_joint
#     - summit_xl_back_left_wheel_joint
#     - summit_xl_back_right_wheel_joint

front_right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: summit_xl_front_right_wheel_joint

front_left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: summit_xl_front_left_wheel_joint

back_right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: summit_xl_back_right_wheel_joint

back_left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: summit_xl_back_left_wheel_joint
